{{- if eq (.Values.tornjak.enabled | toString) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-tornjak.config" . }}
  namespace: {{ include "spire-server.namespace" . }}
data:
  server.conf: |
    server {
      spire_socket_path = "unix:///tmp/spire-server/private/api.sock" # socket to communicate with SPIRE server
      http {
        port = "10080" # opens HTTP listen port at specified container port
      }
      {{- if or (eq (include "spire-tornjak.connectionType" .) "tls") (eq (include "spire-tornjak.connectionType" .) "mtls") }}
      https {
        port = "10443" # container port for TLS connection
        cert = "/opt/spire/server/tls.crt" # TLS server cert
        key  = "/opt/spire/server/tls.key"  # TLS server key
      {{- if eq (include "spire-tornjak.connectionType" .) "mtls" }}
        clientCA = "/opt/spire/user/ca.crt"  # mTLS user CA
      {{- end }}
      }
      {{- end }}
    }

    plugins {
    {{- if .Values.tornjak.config.dataStore }}
      DataStore "sql" {
        plugin_data {
          drivername = "{{ .Values.tornjak.config.dataStore.driver }}"
          filename = "{{ .Values.tornjak.config.dataStore.file }}"
        }
      }
    {{- end }}
    }
{{- end }}
