spire-server:
# None needed now...

spiffe-csi-driver:
  enabled: true
  namespaceOverride: spire-system
  priorityClassName: system-node-critical

spire-agent:
  enabled: true
  namespaceOverride: spire-system
  serviceAccount:
    name: spire-agent
  server:
    namespaceOverride: spire-server
  priorityClassName: system-node-critical

  logLevel: info

spiffe-oidc-discovery-provider:
  enabled: true
  insecureScheme:
    enabled: true
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ALL]
    seccompProfile:
      type: RuntimeDefault
# Everything above would be merged into the charts. Left alone for now for testing.
# Everything below would be what the user would have in their own values.yaml
#


global:
  spire:
    profiles:
    - production
    #- expose-spire-server-ingress-nginx
    #- expose-federation-https-web-ingress-nginx
    #- expose-federation-https-spiffe-ingress-nginx

    clusterName: "example-cluster"
    trustDomain: "example.org"

  telemetry:
    prometheus:
      enabled: true
