nameOverride: ""
fullnameOverride: ""

# subcharts
spire-server:
  nameOverride: server
  bundleConfigMap: &bundleConfigMap spire-bundle

  clusterName: &clusterName "example-cluster"
  trustDomain: &trustDomain "example.org"

  controllerManager:
    enabled: true

spire-agent:
  nameOverride: agent
  bundleConfigMap: *bundleConfigMap

  clusterName: *clusterName
  trustDomain: *trustDomain

csi-driver-main:
  enabled: true
  # @ignored
  socketMacroName: "spire.agent-socket-path.main"

# Useful when you are setting up a Federated spire
csi-driver-upstream:
  enabled: false
  healthChecks:
    port: 9810
  # @ignored
  pluginName: upstream.csi.spiffe.io
  # @ignored
  socketMacroName: "spire.agent-socket-path.upstream"

spiffe-oidc-discovery-provider:
  enabled: false
  trustDomain: *trustDomain
