# You can enable config/features that affect all services here.
global:
  k8s:
    # -- This is the value of your clusters `kubeadm init --service-dns-domain` flag
    clusterDomain: cluster.local
  spire:
    # -- Set the name of the Kubernetes cluster
    clusterName: example-cluster
    # -- Set the trust domain to use for the spiffe identifiers
    trustDomain: example.org
    # -- Override all instances of bundleConfigMap
    bundleConfigMap: ""

#  telemetry:
#    prometheus:
#      enabled: true
#      podMonitor:
#        enabled: true
#        # -- Allows to install the PodMonitor in another namespace then the spire components are installed into.
#        namespace: "kube-prometheus-system"
#        labels: {}

# subcharts
spire-server:
  enabled: true
  nameOverride: server

  controllerManager:
    enabled: true

spire-agent:
  enabled: true
  nameOverride: agent

upstream:
  # -- enable upstream csi driver and agent for use with nested spire.
  enabled: false

upstream-spire-agent:
  nameOverride: agent-upstream
  bundleConfigMap: spire-bundle-upstream

  socketPath: /run/spire/agent-sockets-upstream/spire-agent.sock
  serviceAccount:
    name: spire-agent-upstream
  healthChecks:
    port: 9981

spiffe-csi-driver:
  enabled: true

upstream-spiffe-csi-driver:
  pluginName: upstream.csi.spiffe.io
  agentSocketPath: /run/spire/agent-sockets-upstream/spire-agent.sock
  healthChecks:
    port: 9810

spiffe-oidc-discovery-provider:
  enabled: false
